### ISSUE TITLE
Revisit README file to conclude block and file notion

### ISSUE THREAD

**Issue by shay-berman** [IBM/ubiquity-docker-plugin#25]
same as the ubiquity ticket -> https://github.com/IBM/ubiquity/issues/53
We need to make the README file unify for block and file, because currently its only focus on spectrum scale.

This ticket should be done on branch [update_READMEs_for_unify_block_and_file] and at the end we need to merge it into dev branch when we all approve the docs.

**Comment by shay-berman** [comment]
@aswarke please start work on it and when u finish assign it to me.
Thanks!

**Comment by aswarke** [comment]
@shay-berman assigning this back to you. Made changes to make README generic with md file for each Ubiquity supported storage system . Please review, modify if needed and add content in ibm-block-storage-via-scbe.md
